#ifndef RLFSMSTATESENUM_H
#define RLFSMSTATESENUM_H

#include <string>

namespace RLFSM_NMSPC
{
	enum RLFSMStatesEnum
	{
		RL_OBSRV_CURR_FSM_STATE = 0,
		RL_SEL_ACTION_FSM_STATE,
		RL_PERF_ACTION_FSM_STATE,
		RL_OBSRV_NEXT_FSM_STATE,
		RL_GET_REWARD_FSM_STATE,
		RL_ADJUST_Q_FSM_STATE,
		RL_STATES_NUM
	};
}

#endif